import { planSchema } from "@bitpix/contracts";
import { CompanyStatus, Prisma, prisma } from "@bitpix/database";
import argon2 from "argon2";
import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { z } from "zod";
import { AppError, forbidden } from "../../lib/errors.js";
import { writeAudit } from "../../lib/audit.js";
import { authenticate, requirePermission } from "../auth/auth.guard.js";
import { queueHealth as exportQueueHealth } from "../reports/export-queue.js";
import { webhookQueueCounts } from "../payments/webhook-queue.js";

const companySchema = z.object({ displayName: z.string().trim().min(2).max(120), legalName: z.string().trim().min(2).max(180), slug: z.string().trim().min(2).max(80).regex(/^[a-z0-9-]+$/), timezone: z.string().trim().min(3).max(80), planPublicId: z.uuid(), adminName: z.string().trim().min(2).max(120), adminEmail: z.email().transform((v) => v.toLowerCase()), adminPassword: z.string().min(12).max(128) });
const listQuery = z.object({ page: z.coerce.number().int().positive().default(1), pageSize: z.coerce.number().int().min(1).max(100).default(20), search: z.string().trim().max(120).optional(), status: z.nativeEnum(CompanyStatus).optional() });
async function platformOnly(request: FastifyRequest, reply: FastifyReply) { await authenticate(request, reply); const user = await prisma.user.findUnique({ where: { id: request.auth!.userId }, select: { isPlatformAdmin: true } }); if (!user?.isPlatformAdmin) throw forbidden(); }

export async function platformRoutes(app: FastifyInstance): Promise<void> {
  app.addHook("preHandler", platformOnly);
  app.get("/platform/dashboard", { preHandler: requirePermission("platform.dashboard.read") }, async () => { const month = new Date(); month.setUTCDate(1); month.setUTCHours(0, 0, 0, 0); const [companies, active, suspended, users, payments, amount, failedExports] = await Promise.all([prisma.company.count({ where: { slug: { not: "bitpix-platform" } } }), prisma.company.count({ where: { status: "ACTIVE", slug: { not: "bitpix-platform" } } }), prisma.company.count({ where: { status: "SUSPENDED" } }), prisma.user.count({ where: { isPlatformAdmin: false } }), prisma.pixPayment.count({ where: { paidAt: { gte: month } } }), prisma.pixPayment.aggregate({ where: { paidAt: { gte: month } }, _sum: { amount: true } }), prisma.exportJob.count({ where: { status: "FAILED", requestedAt: { gte: month } } })]); return { data: { companies, activeCompanies: active, suspendedCompanies: suspended, users, paymentsThisMonth: payments, volumeThisMonth: amount._sum.amount?.toFixed(2) ?? "0.00", failedExports } }; });
  app.get("/platform/companies", { preHandler: requirePermission("platform.companies.read") }, async (request) => { const query = listQuery.parse(request.query); const where = { slug: { not: "bitpix-platform" }, ...(query.status ? { status: query.status } : {}), ...(query.search ? { OR: [{ displayName: { contains: query.search, mode: "insensitive" as const } }, { slug: { contains: query.search, mode: "insensitive" as const } }] } : {}) }; const [data, total] = await Promise.all([prisma.company.findMany({ where, select: { publicId: true, displayName: true, legalName: true, slug: true, status: true, timezone: true, createdAt: true, plan: { select: { publicId: true, key: true, name: true } }, subscription: { select: { status: true, currentPeriodEnd: true } }, _count: { select: { users: true, branches: true, pixCharges: true } } }, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * query.pageSize, take: query.pageSize }), prisma.company.count({ where })]); return { data, pagination: { page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) } }; });
  app.post("/platform/companies", { preHandler: requirePermission("platform.companies.create") }, async (request, reply) => { const body = companySchema.parse(request.body); if (await prisma.company.findUnique({ where: { slug: body.slug } })) throw new AppError(409, "COMPANY_EXISTS", "Já existe uma empresa com este identificador."); if (await prisma.user.findUnique({ where: { normalizedEmail: body.adminEmail } })) throw new AppError(409, "USER_EMAIL_EXISTS", "O e-mail informado já está em uso."); const plan = await prisma.plan.findFirst({ where: { publicId: body.planPublicId, status: "ACTIVE" } }); if (!plan) throw new AppError(400, "PLAN_INVALID", "Plano inválido."); const permissions = await prisma.permission.findMany({ where: { key: { not: { startsWith: "platform." } } } }); const passwordHash = await argon2.hash(body.adminPassword, { type: argon2.argon2id }); const created = await prisma.$transaction(async (tx) => { const company = await tx.company.create({ data: { displayName: body.displayName, legalName: body.legalName, slug: body.slug, timezone: body.timezone, planId: plan.id } }); const branch = await tx.branch.create({ data: { companyId: company.id, code: "MATRIZ", name: "Matriz" } }); const role = await tx.role.create({ data: { companyId: company.id, key: "ADMIN", name: "Administrador", isSystem: true } }); await tx.rolePermission.createMany({ data: permissions.map((permission) => ({ companyId: company.id, roleId: role.id, permissionId: permission.id })) }); const user = await tx.user.create({ data: { companyId: company.id, branchId: branch.id, name: body.adminName, email: body.adminEmail, normalizedEmail: body.adminEmail, passwordHash, mustResetPassword: true } }); await tx.userRole.create({ data: { companyId: company.id, userId: user.id, roleId: role.id } }); await tx.companySetting.create({ data: { companyId: company.id } }); await tx.printTemplate.create({ data: { companyId: company.id, scopeKey: "COMPANY_DEFAULT", storeName: company.displayName } }); await tx.subscription.create({ data: { companyId: company.id, planId: plan.id, currentPeriodEnd: new Date(Date.now() + 30 * 86_400_000) } }); return company; }); await writeAudit({ request, companyId: null, branchId: null, action: "platform.company.created", entity: "Company", entityPublicId: created.publicId, after: { displayName: created.displayName, slug: created.slug, plan: plan.key } }); return reply.status(201).send({ data: { publicId: created.publicId, displayName: created.displayName, slug: created.slug, status: created.status } }); });
  app.post<{ Params: { publicId: string } }>("/platform/companies/:publicId/suspend", { preHandler: requirePermission("platform.companies.suspend") }, async (request) => setStatus(request, "SUSPENDED"));
  app.post<{ Params: { publicId: string } }>("/platform/companies/:publicId/activate", { preHandler: requirePermission("platform.companies.update") }, async (request) => setStatus(request, "ACTIVE"));
  app.get("/platform/plans", { preHandler: requirePermission("platform.plans.manage") }, async () => ({ data: await prisma.plan.findMany({ orderBy: { price: "asc" }, include: { _count: { select: { companies: true } } } }) }));
  app.post("/platform/plans", { preHandler: requirePermission("platform.plans.manage") }, async (request, reply) => { const body = planSchema.parse(request.body); const plan = await prisma.plan.create({ data: { key: body.key, name: body.name, description: body.description, price: new Prisma.Decimal(body.priceInCents).div(100), billingPeriod: body.billingPeriod, userLimit: body.userLimit, branchLimit: body.branchLimit, cashRegisterLimit: body.cashRegisterLimit, monthlyChargeLimit: body.monthlyChargeLimit, monthlyExportLimit: body.monthlyExportLimit, features: body.features } }); await writeAudit({ request, companyId: null, action: "platform.plan.created", entity: "Plan", entityPublicId: plan.publicId, after: body }); return reply.status(201).send({ data: plan }); });
  app.get("/platform/health", { preHandler: requirePermission("platform.health.read") }, async () => { const [database, exports, webhooks] = await Promise.all([prisma.$queryRaw`SELECT 1`.then(() => "ok" as const).catch(() => "error" as const), exportQueueHealth(), webhookQueueCounts()]); const failedWebhooks = await prisma.webhookEvent.count({ where: { status: { in: ["FAILED", "DEAD_LETTER"] } } }); return { data: { database, exportQueue: exports, webhookQueue: webhooks, failedWebhooks, checkedAt: new Date().toISOString(), environment: process.env.NODE_ENV ?? "development" } }; });
}
async function setStatus(request: FastifyRequest<{ Params: { publicId: string } }>, status: "ACTIVE" | "SUSPENDED") { const current = await prisma.company.findFirst({ where: { publicId: request.params.publicId, slug: { not: "bitpix-platform" } } }); if (!current) throw new AppError(404, "COMPANY_NOT_FOUND", "Empresa não encontrada."); const saved = await prisma.$transaction(async (tx) => { const company = await tx.company.update({ where: { id: current.id }, data: { status } }); if (status === "SUSPENDED") await tx.userSession.updateMany({ where: { companyId: current.id, revokedAt: null }, data: { revokedAt: new Date() } }); return company; }); await writeAudit({ request, companyId: null, action: status === "SUSPENDED" ? "platform.company.suspended" : "platform.company.activated", entity: "Company", entityPublicId: current.publicId, before: { status: current.status }, after: { status } }); return { data: { publicId: saved.publicId, status: saved.status } }; }
