import { paginationSchema } from "@bitpix/contracts";
import { prisma } from "@bitpix/database";
import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { AppError } from "../../lib/errors.js";
import { authenticate, requirePermission } from "../auth/auth.guard.js";

const auditQuery = paginationSchema.extend({ action: z.string().trim().max(100).optional(), entity: z.string().trim().max(80).optional(), outcome: z.enum(["SUCCESS", "FAILURE"]).optional(), correlationId: z.uuid().optional(), from: z.iso.date().optional(), to: z.iso.date().optional() });
export async function auditRoutes(app: FastifyInstance): Promise<void> {
  app.get("/activity/recent", { preHandler: authenticate }, async (request) => { const canReadAudit = request.auth!.permissions.has("audit.read"); const logs = await prisma.auditLog.findMany({ where: { companyId: request.auth!.companyId, ...(canReadAudit ? {} : { userId: request.auth!.userId }) }, take: 5, orderBy: { createdAt: "desc" }, select: { publicId: true, action: true, outcome: true, createdAt: true, actor: { select: { name: true } } } }); return { data: logs }; });
  app.get("/audit", { preHandler: requirePermission("audit.read") }, async (request) => { const query = auditQuery.parse(request.query); const where = { companyId: request.auth!.companyId, ...(query.action ? { action: { contains: query.action, mode: "insensitive" as const } } : {}), ...(query.entity ? { entity: query.entity } : {}), ...(query.outcome ? { outcome: query.outcome } : {}), ...(query.correlationId ? { correlationId: query.correlationId } : {}), ...(query.from || query.to ? { createdAt: { ...(query.from ? { gte: new Date(`${query.from}T00:00:00Z`) } : {}), ...(query.to ? { lte: new Date(`${query.to}T23:59:59.999Z`) } : {}) } } : {}) }; const [data, total] = await Promise.all([prisma.auditLog.findMany({ where, select: { publicId: true, action: true, entity: true, entityPublicId: true, outcome: true, correlationId: true, ipAddress: true, createdAt: true, actor: { select: { publicId: true, name: true } }, branch: { select: { publicId: true, name: true } } }, take: query.pageSize, skip: (query.page - 1) * query.pageSize, orderBy: { createdAt: "desc" } }), prisma.auditLog.count({ where })]); return { data, pagination: { page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) } }; });
  app.get<{ Params: { publicId: string } }>("/audit/:publicId", { preHandler: requirePermission("audit.details.read") }, async (request) => { const log = await prisma.auditLog.findFirst({ where: { companyId: request.auth!.companyId, publicId: request.params.publicId }, select: { publicId: true, action: true, entity: true, entityPublicId: true, outcome: true, correlationId: true, ipAddress: true, userAgent: true, before: true, after: true, metadata: true, createdAt: true, actor: { select: { publicId: true, name: true, email: true } }, branch: { select: { publicId: true, name: true } } } }); if (!log) throw new AppError(404, "AUDIT_NOT_FOUND", "Registro de auditoria não encontrado."); return { data: log }; });
}
