"use client";
import { Download, FileSpreadsheet, LoaderCircle, Search } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3333";
const types = { sales: "Vendas", payments: "Pagamentos", charges: "Cobranças", "cash-sessions": "Sessões de caixa", "cash-movements": "Movimentos", reconciliation: "Conciliação" } as const;
const exportTypes: Record<keyof typeof types, string> = { sales: "SALES", payments: "PAYMENTS", charges: "CHARGES", "cash-sessions": "CASH_SESSIONS", "cash-movements": "CASH_MOVEMENTS", reconciliation: "RECONCILIATION" };
export function ReportConsole({ type, rows, total, initialSearch, from, to, operators = [], operator = "" }: { type: keyof typeof types; rows: Array<Record<string,string|number|null>>; total: number; initialSearch: string; from: string; to: string; operators?: Array<{ publicId: string; name: string }>; operator?: string }) {
  const router = useRouter(); const [working, setWorking] = useState<string|null>(null); const [notice, setNotice] = useState("");
  const filter = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const op = String(data.get("operator") ?? ""); router.push(`/relatorios?type=${type}&from=${data.get("from")}&to=${data.get("to")}&search=${encodeURIComponent(String(data.get("search") ?? ""))}${op?`&operator=${op}`:""}`); };
  const exportFile = async (format: "CSV"|"XLSX"|"PDF") => { setWorking(format); setNotice(""); try { const response = await fetch(`${apiUrl}/api/v1/reports/exports`, { method:"POST", credentials:"include", headers:{"content-type":"application/json"}, body:JSON.stringify({ reportType:exportTypes[type], format, filters:{ page:1,pageSize:50,from,to,...(initialSearch?{search:initialSearch}:{}),...(operator?{operatorPublicId:operator}:{}) } }) }); if(!response.ok) throw new Error("Não foi possível iniciar a exportação."); const job = await response.json() as {data:{publicId:string}}; for(let attempt=0;attempt<30;attempt++){ await new Promise((resolve)=>setTimeout(resolve,500)); const statusResponse=await fetch(`${apiUrl}/api/v1/reports/exports/${job.data.publicId}`,{credentials:"include"}); const status=await statusResponse.json() as {data:{status:string;downloadUrl:string|null;errorMessage:string|null}}; if(status.data.status==="COMPLETED"&&status.data.downloadUrl){ window.location.assign(`${apiUrl}${status.data.downloadUrl}`); setNotice("Arquivo gerado com sucesso."); return; } if(status.data.status==="FAILED") throw new Error(status.data.errorMessage??"Falha na exportação."); } throw new Error("A exportação continua em processamento. Consulte as notificações."); } catch(error){ setNotice(error instanceof Error?error.message:"Falha na exportação."); } finally { setWorking(null); } };
  const columns = rows[0] ? Object.keys(rows[0]) : [];
  return <><div className="report-tabs">{Object.entries(types).map(([key,label])=><a data-active={key===type} href={`/relatorios?type=${key}`} key={key}>{label}</a>)}</div>
    <form className="card report-filters" onSubmit={filter}><label><span>De</span><input type="date" name="from" defaultValue={from}/></label><label><span>Até</span><input type="date" name="to" defaultValue={to}/></label><label className="report-search"><span>Busca</span><div><Search size={17}/><input name="search" defaultValue={initialSearch} placeholder="Código ou identificador"/></div></label>{operators.length>0&&<label><span>Atendente</span><select name="operator" defaultValue={operator} className="field-input"><option value="">Geral (todos)</option>{operators.map((op)=><option key={op.publicId} value={op.publicId}>{op.name}</option>)}</select></label>}<button className="primary-button" type="submit">Aplicar filtros</button></form>
    <div className="report-toolbar"><p><strong>{total}</strong> registro{total===1?"":"s"} encontrado{total===1?"":"s"}</p><div>{(["CSV","XLSX","PDF"] as const).map((format)=><button className="secondary-button" type="button" disabled={working!==null} onClick={()=>void exportFile(format)} key={format}>{working===format?<LoaderCircle className="spin" size={16}/>:format==="XLSX"?<FileSpreadsheet size={16}/>:<Download size={16}/>} {format}</button>)}</div></div>{notice&&<p className="inline-notice">{notice}</p>}
    <section className="card data-card">{rows.length?<div className="table-scroll"><table><thead><tr>{columns.map((column)=><th key={column}>{humanize(column)}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{columns.map((column)=><td key={column}>{formatValue(row[column])}</td>)}</tr>)}</tbody></table></div>:<div className="empty-state"><FileSpreadsheet size={28}/><p>Nenhum dado real encontrado com estes filtros.</p></div>}</section></>;
}
function humanize(value:string){return value.replace(/([A-Z])/g," $1").replace(/^./,(letter)=>letter.toUpperCase());}
function formatValue(value:string|number|null|undefined){if(value===null||value===undefined)return "—"; if(typeof value==="string"&&/^\d{4}-\d{2}-\d{2}T/.test(value))return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)); return String(value);}
