import { createBranchSchema, paginationSchema, updateBranchSchema } from "@bitpix/contracts";
import { prisma } from "@bitpix/database";
import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { AppError } from "../../lib/errors.js";
import { writeAudit } from "../../lib/audit.js";
import { authenticate, requireAnyPermission } from "../auth/auth.guard.js";
import { enforceCompanyLimit } from "../platform/plan-limits.js";

const branchQuery = paginationSchema.extend({ search: z.string().trim().max(120).optional(), active: z.coerce.boolean().optional() });
const branchSelect = { publicId: true, code: true, name: true, active: true, timezone: true, addressLine1: true, addressLine2: true, city: true, state: true, postalCode: true, createdAt: true, _count: { select: { users: true, cashRegisters: true } } } as const;

export async function tenancyRoutes(app: FastifyInstance): Promise<void> {
  app.get("/companies/current", { preHandler: authenticate }, async (request) => ({ data: await prisma.company.findUniqueOrThrow({ where: { id: request.auth!.companyId }, select: { publicId: true, displayName: true, legalName: true, slug: true, status: true, timezone: true, plan: { select: { key: true, name: true } } } }) }));
  app.get("/branches", { preHandler: authenticate }, async (request) => { const query = branchQuery.parse(request.query); const where = { companyId: request.auth!.companyId, ...(query.active === undefined ? {} : { active: query.active }), ...(query.search ? { OR: [{ name: { contains: query.search, mode: "insensitive" as const } }, { code: { contains: query.search, mode: "insensitive" as const } }] } : {}) }; const [data, total] = await Promise.all([prisma.branch.findMany({ where, select: branchSelect, orderBy: { name: "asc" }, skip: (query.page - 1) * query.pageSize, take: query.pageSize }), prisma.branch.count({ where })]); return { data, pagination: { page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) } }; });

  app.post("/branches", { preHandler: requireAnyPermission("branches.create", "branches.manage") }, async (request, reply) => { const body = createBranchSchema.parse(request.body); const companyId = request.auth!.companyId; await enforceCompanyLimit(companyId, "branches"); if (await prisma.branch.findUnique({ where: { companyId_code: { companyId, code: body.code.toUpperCase() } } })) throw new AppError(409, "BRANCH_CODE_EXISTS", "Já existe uma filial com este código."); const branch = await prisma.branch.create({ data: { companyId, code: body.code.toUpperCase(), name: body.name }, select: branchSelect }); await writeAudit({ request, action: "branch.created", entity: "Branch", entityPublicId: branch.publicId, after: branch }); return reply.status(201).send({ data: branch }); });

  app.patch<{ Params: { publicId: string } }>("/branches/:publicId", { preHandler: requireAnyPermission("branches.update", "branches.manage") }, async (request) => { const body = updateBranchSchema.parse(request.body); const companyId = request.auth!.companyId; const current = await prisma.branch.findFirst({ where: { companyId, publicId: request.params.publicId } }); if (!current) throw new AppError(404, "BRANCH_NOT_FOUND", "Filial não encontrada."); const code = body.code?.toUpperCase(); if (code && code !== current.code && await prisma.branch.findUnique({ where: { companyId_code: { companyId, code } } })) throw new AppError(409, "BRANCH_CODE_EXISTS", "Já existe uma filial com este código."); const data = { ...(body.name ? { name: body.name } : {}), ...(code ? { code } : {}), ...(body.timezone ? { timezone: body.timezone } : {}), ...(body.addressLine1 === undefined ? {} : { addressLine1: body.addressLine1 }), ...(body.addressLine2 === undefined ? {} : { addressLine2: body.addressLine2 }), ...(body.city === undefined ? {} : { city: body.city }), ...(body.state === undefined ? {} : { state: body.state }), ...(body.postalCode === undefined ? {} : { postalCode: body.postalCode }) }; const saved = await prisma.branch.update({ where: { id: current.id }, data, select: branchSelect }); await writeAudit({ request, action: "branch.updated", entity: "Branch", entityPublicId: saved.publicId, before: current, after: saved }); return { data: saved }; });

  app.post<{ Params: { publicId: string } }>("/branches/:publicId/disable", { preHandler: requireAnyPermission("branches.disable", "branches.manage") }, async (request) => { const companyId = request.auth!.companyId; const branch = await prisma.branch.findFirst({ where: { companyId, publicId: request.params.publicId } }); if (!branch) throw new AppError(404, "BRANCH_NOT_FOUND", "Filial não encontrada."); if (await prisma.cashSession.count({ where: { companyId, branchId: branch.id, status: "OPEN" } })) throw new AppError(409, "BRANCH_HAS_OPEN_CASH", "Feche os caixas abertos antes de desativar a filial."); const saved = await prisma.branch.update({ where: { id: branch.id }, data: { active: false }, select: branchSelect }); await writeAudit({ request, action: "branch.disabled", entity: "Branch", entityPublicId: branch.publicId, before: { active: branch.active }, after: { active: false } }); return { data: saved }; });

  app.post<{ Params: { publicId: string } }>("/branches/:publicId/enable", { preHandler: requireAnyPermission("branches.update", "branches.manage") }, async (request) => { const branch = await prisma.branch.findFirst({ where: { companyId: request.auth!.companyId, publicId: request.params.publicId } }); if (!branch) throw new AppError(404, "BRANCH_NOT_FOUND", "Filial não encontrada."); const saved = await prisma.branch.update({ where: { id: branch.id }, data: { active: true }, select: branchSelect }); await writeAudit({ request, action: "branch.enabled", entity: "Branch", entityPublicId: branch.publicId }); return { data: saved }; });
}
